# Generated by Django 5.1.15 on 2026-09-01 21:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "rate_date",
                    models.DateField(
                        primary_key=True, serialize=False, verbose_name="rate date"
                    ),
                ),
                (
                    "usd_try_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="USD/TRY rate",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        default="efektif satış", max_length=40, verbose_name="rate type"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="TCMB", max_length=40, verbose_name="source"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now=True, verbose_name="fetched at"),
                ),
            ],
            options={
                "verbose_name": "exchange rate",
                "verbose_name_plural": "exchange rates",
                "ordering": ("-rate_date",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "amount_try",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount (TRY)",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="exchange rate used",
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="amount (USD)",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        max_length=120, verbose_name="bank reference / receipt no"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="payment date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="receipt file",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declared_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="declared by",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ("-payment_date", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "APPROVED")),
                        fields=("order",),
                        name="one_approved_payment_per_order",
                    )
                ],
            },
        ),
    ]
