# Generated by Django 5.1.15 on 2026-09-02 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="chf_try_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Used only to convert Swiss-Franc list prices to USD.",
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="CHF/TRY rate",
            ),
        ),
    ]
