# Generated by Django 5.1.15 on 2026-09-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="dealer name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="dealer code"
                    ),
                ),
                (
                    "tax_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="tax number"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="tax office"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="city"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="contact person"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "dealer",
                "verbose_name_plural": "dealers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DomainDealerMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "email_domain",
                    models.CharField(
                        max_length=190, unique=True, verbose_name="email domain"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="dealers.dealer",
                        verbose_name="dealer",
                    ),
                ),
            ],
            options={
                "verbose_name": "domain mapping",
                "verbose_name_plural": "domain mappings",
                "ordering": ("email_domain",),
            },
        ),
    ]
