# Generated by Django 5.1.15 on 2026-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Square images work best; shown at 40x40 pixels in lists.",
                null=True,
                upload_to="dealer_logos/",
                verbose_name="dealer logo",
            ),
        ),
    ]
