# Generated by Django 5.1.15 on 2026-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_devicemodel_product_device_model"),
        ("dealers", "0002_dealer_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="allowed_device_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restricts the catalogue to these device models. Leave empty to allow every device model (no restriction).",
                related_name="dealers",
                to="catalog.devicemodel",
                verbose_name="allowed device models",
            ),
        ),
    ]
