# Generated by Django 5.1.15 on 2026-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0003_dealer_allowed_device_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="mikro_cari_kodu",
            field=models.CharField(
                blank=True,
                help_text="The dealer's customer (cari) code in Mikro. Required before an order for this dealer can be sent to Mikro.",
                max_length=25,
                verbose_name="Mikro customer code",
            ),
        ),
    ]
