# Generated by Django 5.1.15 on 2026-09-02 12:51

import django.db.models.deletion
import integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VatRateMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        unique=True,
                        verbose_name="VAT rate (%)",
                    ),
                ),
                (
                    "mikro_vergi_pntr",
                    models.PositiveIntegerField(
                        verbose_name="Mikro VAT pointer (sip_vergi_pntr)"
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT pointer mapping",
                "verbose_name_plural": "VAT pointer mappings",
                "ordering": ("vat_rate",),
            },
        ),
        migrations.CreateModel(
            name="MikroSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="While off, approved orders are not queued for Mikro at all.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mikro API key"
                    ),
                ),
                (
                    "firma_kodu",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="company code (FirmaKodu)",
                    ),
                ),
                (
                    "kullanici_kodu",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="user code (KullaniciKodu)",
                    ),
                ),
                (
                    "sifre",
                    models.CharField(
                        blank=True,
                        help_text="The plain Mikro user password. Mikro requires it hashed with the day's date (MD5 of “YYYY-MM-DD ” + password) on every request, recomputed fresh each time - this is done automatically and the plain value is never shown again once saved.",
                        max_length=255,
                        verbose_name="password (Sifre)",
                    ),
                ),
                (
                    "calisma_yili",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mikro's fiscal year. Update this when the fiscal year rolls over.",
                        verbose_name="working year (CalismaYili)",
                    ),
                ),
                (
                    "depo_no",
                    models.PositiveIntegerField(
                        default=0, verbose_name="warehouse number (sip_depono)"
                    ),
                ),
                (
                    "evrak_seri",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="document series (sip_evrakno_seri)",
                    ),
                ),
                (
                    "sip_tip",
                    models.CharField(
                        default="1", max_length=10, verbose_name="order type (sip_tip)"
                    ),
                ),
                (
                    "sip_cins",
                    models.CharField(
                        default="0", max_length=10, verbose_name="order kind (sip_cins)"
                    ),
                ),
                (
                    "birim_pntr",
                    models.PositiveIntegerField(
                        default=1, verbose_name="default unit pointer (sip_birim_pntr)"
                    ),
                ),
                (
                    "vergisiz_fl",
                    models.BooleanField(
                        default=False,
                        verbose_name="prices are VAT-exclusive (sip_vergisiz_fl)",
                    ),
                ),
                (
                    "para_birimi",
                    models.CharField(
                        choices=[("USD", "USD"), ("TRY", "TRY")],
                        default="TRY",
                        help_text="Order amounts are converted to this currency before being sent.",
                        max_length=3,
                        verbose_name="currency sent to Mikro",
                    ),
                ),
                (
                    "connector_token",
                    models.CharField(
                        default=integrations.models._generate_token,
                        editable=False,
                        max_length=64,
                        verbose_name="connector token",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mikro settings",
                "verbose_name_plural": "Mikro settings",
            },
        ),
    ]
