# Generated by Django 5.1.15 on 2026-09-01 21:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="product code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="brand"
                    ),
                ),
                (
                    "tests_per_pack",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tests per pack"
                    ),
                ),
                (
                    "base_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="list price (USD)",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="VAT rate (%)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="DealerSpecialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="special price (USD)",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_prices",
                        to="dealers.dealer",
                        verbose_name="dealer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_prices",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "dealer special price",
                "verbose_name_plural": "dealer special prices",
                "ordering": ("dealer__name", "product__code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dealer", "product"), name="unique_dealer_product_price"
                    )
                ],
            },
        ),
    ]
