# Generated by Django 5.1.15 on 2026-09-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="device model"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="brand"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "device model",
                "verbose_name_plural": "device models",
                "ordering": ("brand", "name"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="device_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Used to restrict which dealers may order this product.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.devicemodel",
                verbose_name="device model",
            ),
        ),
    ]
