# Generated by Django 5.1.15 on 2026-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_devicemodel_product_device_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mikro_stok_kodu",
            field=models.CharField(
                blank=True,
                help_text="This product's stock (stok) code in Mikro. Required before an order containing it can be sent to Mikro.",
                max_length=64,
                verbose_name="Mikro stock code",
            ),
        ),
    ]
