# Generated by Django 5.1.15 on 2026-09-02 18:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_mikro_stok_kodu"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="list_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Only used when the list price currency above isn't USD - the supplier's own price, before conversion.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="list price (native currency)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("CHF", "CHF")],
                default="USD",
                help_text="The currency the supplier actually quotes this product in. base_price_usd stays the authoritative USD figure either way.",
                max_length=3,
                verbose_name="list price currency",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.CharField(
                choices=[
                    ("DEVICE", "Device"),
                    ("CONSUMABLE", "Consumable"),
                    ("SPARE_PART", "Spare part"),
                ],
                default="CONSUMABLE",
                max_length=12,
                verbose_name="product group",
            ),
        ),
    ]
