# Generated by Django 5.1.15 on 2026-09-01 21:46

import django.core.validators
import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("dealers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumberSequence",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="year"
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="last issued number"
                    ),
                ),
            ],
            options={
                "verbose_name": "order number sequence",
                "verbose_name_plural": "order number sequences",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_PAYMENT", "Awaiting payment approval"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        protected=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="subtotal (USD)",
                    ),
                ),
                (
                    "vat_total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="VAT total (USD)",
                    ),
                ),
                (
                    "total_amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="grand total (USD)",
                    ),
                ),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("NOT_SHIPPED", "Not shipped"),
                            ("SHIPPED", "Shipped"),
                        ],
                        default="NOT_SHIPPED",
                        max_length=20,
                        verbose_name="shipment status",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="shipped at"
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="tracking number"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="carrier"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                ("note", models.TextField(blank=True, verbose_name="dealer note")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="dealers.dealer",
                        verbose_name="dealer",
                    ),
                ),
                (
                    "shipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipped_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="shipped by",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=64, verbose_name="product code"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="product name"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=120, verbose_name="brand"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="unit price (USD)"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="VAT rate (%)"
                    ),
                ),
                (
                    "line_total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="line total (USD)",
                    ),
                ),
                (
                    "vat_amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="VAT amount (USD)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_PAYMENT", "Awaiting payment approval"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_PAYMENT", "Awaiting payment approval"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="to status",
                    ),
                ),
                (
                    "order_no_at_change",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="order number at the time",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="changed at"),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order status change",
                "verbose_name_plural": "order status history",
                "ordering": ("-changed_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["dealer", "status"], name="orders_orde_dealer__278514_idx"
            ),
        ),
    ]
