# Generated by Django 5.1.15 on 2026-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mikro_reference",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Mikro reference"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mikro_sync_error",
            field=models.TextField(blank=True, verbose_name="Mikro sync error"),
        ),
        migrations.AddField(
            model_name="order",
            name="mikro_sync_status",
            field=models.CharField(
                choices=[
                    ("NOT_QUEUED", "Not queued"),
                    ("PENDING", "Waiting to be sent"),
                    ("SYNCED", "Sent to Mikro"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_QUEUED",
                max_length=12,
                verbose_name="Mikro sync status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mikro_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="sent to Mikro at"
            ),
        ),
    ]
