# Generated by Django 5.1.15 on 2026-09-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_SUBMITTED", "Order submitted to finance"),
                            ("PAYMENT_APPROVED", "Payment approved"),
                            ("PAYMENT_REJECTED", "Payment rejected"),
                            ("ORDER_SHIPPED", "Order shipped"),
                            ("USER_REGISTERED", "New user awaiting approval"),
                            ("USER_APPROVED", "User account approved"),
                        ],
                        max_length=40,
                        verbose_name="event",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("INAPP", "In-app")],
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sent at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="detail")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification log",
                "verbose_name_plural": "notification logs",
                "ordering": ("-sent_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_SUBMITTED", "Order submitted to finance"),
                            ("PAYMENT_APPROVED", "Payment approved"),
                            ("PAYMENT_REJECTED", "Payment rejected"),
                            ("ORDER_SHIPPED", "Order shipped"),
                            ("USER_REGISTERED", "New user awaiting approval"),
                            ("USER_APPROVED", "User account approved"),
                        ],
                        max_length=40,
                        verbose_name="event",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Turkish"), ("en", "English")],
                        default="tr",
                        max_length=5,
                        verbose_name="language",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="email subject"),
                ),
                ("email_body_template", models.TextField(verbose_name="email body")),
                ("inapp_body_template", models.TextField(verbose_name="in-app body")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
                "ordering": ("event_type", "language"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_type", "language"),
                        name="unique_event_language_template",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_SUBMITTED", "Order submitted to finance"),
                            ("PAYMENT_APPROVED", "Payment approved"),
                            ("PAYMENT_REJECTED", "Payment rejected"),
                            ("ORDER_SHIPPED", "Order shipped"),
                            ("USER_REGISTERED", "New user awaiting approval"),
                            ("USER_APPROVED", "User account approved"),
                        ],
                        max_length=40,
                        verbose_name="event",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="link"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    )
                ],
            },
        ),
    ]
