# Generated by Django 5.1.15 on 2026-09-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="While off, notification emails use the fallback configured on the server (the console backend in development).",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP host"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP port"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP password"
                    ),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="use TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="use SSL")),
                (
                    "from_email",
                    models.CharField(
                        blank=True,
                        help_text='Example: "BASH Medikal" <noreply@example.com>',
                        max_length=255,
                        verbose_name="from address",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "email settings",
                "verbose_name_plural": "email settings",
            },
        ),
    ]
