# Generated by Django 5.1.15 on 2026-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsettings",
            name="graph_client_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Azure application (client) ID"
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="graph_client_secret",
            field=models.CharField(
                blank=True,
                help_text="The app registration's client secret value. Needs the Mail.Send application permission on Microsoft Graph, with admin consent granted.",
                max_length=255,
                verbose_name="Azure client secret",
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="graph_tenant_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Azure tenant ID"
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("SMTP", "SMTP"),
                    ("MS_GRAPH", "Microsoft Graph (Office 365)"),
                ],
                default="SMTP",
                help_text="Use Microsoft Graph instead of SMTP when the Office 365 tenant's Security Defaults policy blocks basic SMTP authentication.",
                max_length=10,
                verbose_name="sending method",
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="from_email",
            field=models.CharField(
                blank=True,
                help_text='Example: "BASH Medikal" <noreply@example.com>. With Microsoft Graph, this must be a real mailbox the app registration is allowed to send as.',
                max_length=255,
                verbose_name="from address",
            ),
        ),
    ]
