# Generated by Django 5.1.15 on 2026-09-03 08:09

from django.db import migrations, models

#: Reproduces exactly what was hard-coded in notifications.services before
#: this table existed, so nothing changes for an existing install until an
#: administrator visits System Settings and adjusts a role's routing.
DEFAULT_ROUTING = {
    "ORDER_SUBMITTED": {"ADMIN", "FINANCE"},
    "PAYMENT_APPROVED": {"ADMIN", "LOGISTICS", "DEALER"},
    "PAYMENT_REJECTED": {"ADMIN", "DEALER"},
    "ORDER_SHIPPED": {"ADMIN", "DEALER"},
}
ALL_ROLES = ("ADMIN", "FINANCE", "LOGISTICS", "MANAGEMENT", "DEALER")


def seed_default_routing(apps, schema_editor):
    EmailRoutingRule = apps.get_model("notifications", "EmailRoutingRule")
    EmailRoutingRule.objects.bulk_create(
        EmailRoutingRule(
            event_type=event_type, role=role, email_enabled=role in enabled_roles
        )
        for event_type, enabled_roles in DEFAULT_ROUTING.items()
        for role in ALL_ROLES
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailsettings_graph_client_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_SUBMITTED", "Order submitted to finance"),
                            ("PAYMENT_APPROVED", "Payment approved"),
                            ("PAYMENT_REJECTED", "Payment rejected"),
                            ("ORDER_SHIPPED", "Order shipped"),
                            ("USER_REGISTERED", "New user awaiting approval"),
                            ("USER_APPROVED", "User account approved"),
                        ],
                        max_length=40,
                        verbose_name="event",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("FINANCE", "Finance"),
                            ("LOGISTICS", "Logistics"),
                            ("MANAGEMENT", "Management"),
                            ("DEALER", "Dealer"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="send email"),
                ),
            ],
            options={
                "verbose_name": "email routing rule",
                "verbose_name_plural": "email routing rules",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_type", "role"), name="unique_email_routing_rule"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_default_routing, noop),
    ]
